services:
  build:
    build: .
    environment:
      - DEVKITPRO=/opt/devkitpro
      - DEVKITARM=/opt/devkitpro/devkitA64
    volumes:
      - .:/app
      - /app/build
    working_dir: /app
    command: bash -c "make clean && make"